force-app/main/default/objects/mtr_Command__mdt/mtr_Command__mdt.object-meta.xml
<CustomObject>
    <description>Arbitrary blocks of Apex code intended to be run in a specific phase, only one time.</description>
    <label>Command</label>
    <pluralLabel>Commands</pluralLabel>
</CustomObject>

force-app/main/default/objects/mtr_Command__mdt/fields/mtr_ApexClass__c.field-meta.xml
<CustomField>
    <fullName>mtr_ApexClass__c</fullName>
    <description>The implementation of mtr_ICommand to execute during the chosen phase.</description>
    <inlineHelpText>The implementation of mtr_ICommand to execute during the chosen phase.</inlineHelpText>
    <label>Apex Class</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mtr_Command__mdt/fields/mtr_Phase__c.field-meta.xml
<CustomField>
    <fullName>mtr_Phase__c</fullName>
    <description>The phase for this command to execute during.</description>
    <inlineHelpText>The phase for this command to execute during.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>mtr_CommandPhase__mdt</referenceTo>
    <relationshipLabel>Commands</relationshipLabel>
    <relationshipName>Commands</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/mtr_CommandRunLog__c/mtr_CommandRunLog__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains details of commands executed per-phase.</description>
    <label>Command Run Log</label>
</CustomObject>

force-app/main/default/objects/mtr_CommandRunLog__c/fields/mtr_Command__c.field-meta.xml
<CustomField>
    <fullName>mtr_Command__c</fullName>
    <description>The command which was run</description>
    <label>Command</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mtr_CommandRunLog__c/fields/mtr_Log__c.field-meta.xml
<CustomField>
    <fullName>mtr_Log__c</fullName>
    <description>Any relevant details related to the execution.</description>
    <inlineHelpText>Any relevant details related to the execution.</inlineHelpText>
    <label>Log</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/mtr_CommandRunLog__c/fields/mtr_Phase__c.field-meta.xml
<CustomField>
    <fullName>mtr_Phase__c</fullName>
    <description>The phase for which the command was run.</description>
    <inlineHelpText>The phase for which the command was run.</inlineHelpText>
    <label>Phase</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/mtr_CommandServiceTest.cls
@isTest
private class mtr_CommandServiceTest {
    @isTest
    private static void runPostDeploy_noneToRun_expectNoneRun() {
        Test.startTest();
        mtr_CommandService.Instance.runPostDeploy();
        Test.stopTest();

        System.assertNotEquals(null, mtr_CommandService.Instance.toRun, 'Did not expect null commands.');
        System.assertEquals(0, mtr_CommandService.Instance.toRun.size(), 'Expected no commands run.');
    }

    @isTest
    private static void runPostDeploy_withCommands_expectRun() {
        mtr_Command__mdt mockCommand = new mtr_Command__mdt(
            DeveloperName = 'Test',
            mtr_ApexClass__c = 'mtr_MockCommand');

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        mtr_CommandSelector mockSelector = (mtr_CommandSelector) mocks.mock(mtr_CommandSelector.class);
        mtr_CommandSelector.mockInstance = mockSelector;

        mocks.startStubbing();
        mocks.when(mockSelector.selectIncompleteByPhase((Set<String>) fflib_Match.anyObject()))
            .thenReturn(new List<mtr_Command__mdt> { mockCommand });
        mocks.stopStubbing();

        Test.startTest();
        mtr_CommandService.Instance.runPostDeploy();
        Test.stopTest();

        System.assertNotEquals(null, mtr_CommandService.Instance.toRun, 'Did not expect null commands.');
        System.assertEquals(1, mtr_CommandService.Instance.toRun.size(), 'Expected one command.');

        mtr_Command runCommand = mtr_CommandService.Instance.toRun[0];

        mtr_MockCommand actualMockCommand = (mtr_MockCommand) (runCommand.Implementation);

        System.assert(actualMockCommand.hasRun, 'Expected executed.');

        List<mtr_CommandRunLog__c> runLogs = 
            [SELECT mtr_Command__c, mtr_Phase__c, mtr_Log__c FROM mtr_CommandRunLog__c];

        System.assertEquals(1, runLogs.size(), 'Expected one log.');

        mtr_CommandRunLog__c runLog = runLogs[0];

        System.assertEquals('Test', runLog.mtr_Command__c, 'Expected the correct command.');
        System.assertEquals('Unknown', runLog.mtr_Phase__c, 'Expected the correct phase.');
        System.assertEquals('Successful.', runLog.mtr_Log__c, 'Expected the correct log.');
    }
}